smartcontract-one:
	mkdir -p contracts
	cp ../src/contracts/SmartContract.sol contracts/
	npx hardhat test test_smart_contract.js --grep 'step 1'

smartcontract-two:
	mkdir -p contracts
	cp ../src/contracts/SmartContract.sol contracts/
	npx hardhat test test_smart_contract.js --grep 'step 2'
